# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft / Fabric versions for 1.21.11
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.16.10

fabric_version=0.141.2+1.21.11

# Mod properties
mod_version=1.0.0
maven_group=com.example
archives_base_name=lspecs
